apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarea5-deployment
  namespace: devops
  labels:
    app: tarea5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tarea5
  template:
    metadata:
      labels:
        app: tarea5
    spec:
      containers:
      - name: tarea5
        image: localhost:8082/tarea5:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env: 
        - name: USERNAME
          valueFrom: 
            configMapKeyRef:
              name: tarea5
              key: USERNAME
        - name: API_KEY 
          valueFrom :
            secretKeyRef:
              name: tarea5
              key: API_KEY    

      imagePullSecrets: 
      - name : nexus-regcred
