apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarea5-deployment
  namespace: devops
  labels:
    app: tarea5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tarea5
  template:
    metadata:
      labels:
        app: tarea5
    spec:
      containers:
      - name: tarea5
        image: localhost:8082/tarea5:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env: 
        - name: USERNAME
          valueFrom: 
            configMapKeyRef:
              name: tarea5
              key: USERNAME
        - name: API_KEY 
          valueFrom :
            secretKeyRef:
              name: tarea5
              key: API_KEY    

      imagePullSecrets: 
      - name : nexus-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tarea5-svc
  namespace: devops 
  labels:
    app: tarea5
spec:
  selector:
    app: tarea5
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3001

---
apiVersion:  networking.k8s.io/v1
kind: Ingress 
metadata:
  name: tarea5-ingress 
  namespace: devops 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec: 
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /tarea5-path(/|$)(.*)
        pathType: ImplementationSpecific
        backend: 
          service:
            name:  tarea5-svc
            port:
              number: 80 